baseURL = "https://kalaylienes.github.io/hugo_blog/"
languageCode = "tr-tr"
title = "IARVR 25/26"
theme = "hugo-brewm"
author = { name = "kalaylienes" }

enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  description = "IARVR25/26 blog"
  HideHugoCredit = true
  extMeta = true

[outputs]
  home = [ "HTML", "JSON" ]

disableKinds = ["RSS"]